Fix build: add missing #include <QTimeZone>
Amends 00a86d9d2c12aa4e774b1d2c9aec3743db985876.

qprotobufwellknowntypesjsonserializers.cpp:37:69: error: incomplete type
‘QTimeZone’ used in nested name specifier

Change-Id: Ie6dbe21b4790239c8379fffdb5ccf0743f7f3e00
Reviewed-by: Alexey Edelev <alexey.edelev@qt.io>